### ISSUE TITLE
Implement User profile - view [Group 2]

### ISSUE THREAD

**Issue by almeida1492** [intesys/medimemo-uni2grow-2024#10]
https://www.figma.com/design/u3QbbGOEuDUcnEZSngo9EG/Oh---MediMemo-UI?node-id=13-60&t=bdL1k8xoy6YDsH3o-4

Call api GET /contacts/:id

Implement actions for red buttons and top right menu.

![Image](https://github.com/user-attachments/assets/f9278d93-c725-4c55-bea9-372c9a669a71)

**Comment by ArnaudFonzam** [comment]
already done
