### ISSUE TITLE
Implement View medicine details [Group 2]

### ISSUE THREAD

**Issue by almeida1492** [intesys/medimemo-uni2grow-2024#13]
https://www.figma.com/design/u3QbbGOEuDUcnEZSngo9EG/Oh---MediMemo-UI?node-id=50-1259&m=dev

Fetch medicine data by calling: GET /medicines/:id

<img src="https://github.com/user-attachments/assets/83a70ce1-5691-4271-80d4-e4e95ae503eb" height="500px"/>

**Comment by duvaldev203** [comment]
Already Merged
