### ISSUE TITLE
Initialize mock server with dev server [GROUP 1]

### ISSUE THREAD

**Issue by almeida1492** [intesys/medimemo-uni2grow-2024#38]
The `npm run dev` script should initialize both the mock and dev servers. Once it is set up, we expect the submit event handler on the **Login page** to trigger a call that will be intercepted by the mock server and give back mock data. We must use it to emulate an authentication process and then move on to the **Medicines page**. This structure might be reused for every other HTTP call when the app runs on the dev server.

**Login page** failing to perform HTTP call:
![Image](https://github.com/user-attachments/assets/07dc200c-adf0-414f-97c9-2f9024c38a78)

**Comment by gitsupermel** [comment]
Already done !
